### PR TITLE
UI topicbranch 20141111

### PR DESCRIPTION
**Pull request by gforcenova**
Pull Request for updating the UI

### CODE REVIEW

**Comment by rotsuya** [comment]
@gforcenova 
Please update Japanese page with #2 .
This is Japanese sentence. Square brackets mean input forms or buttons.

---

まず、チャンネル[1234|変更]を決めましょう。

イベント主催者は
[ビューワを起動]
し、スクリーンに表示しましょう。

イベント参加者は
[カメラを起動]
し、自分の顔をスクリーンに映しましょう。

カメラのアドレス [is.gd/html5jt#1234] をコピーできます。
[カメラのアドレスをメールでシェア] できます。

**Comment by rotsuya** [comment]
@gforcenova
I would like to test about #4 with local network. Could you add `172.16.0.154` to allowed domain with SkyWay Dashboard? That is today's my Mac's private IP address.

**Comment by gforcenova** [comment]
`172.16.0.154` を追加しました

**Comment by rotsuya** [comment]
I confirmed #9 is fixed. We also need to test after deploy to https://jt.skyway.io/ .

**Comment by rotsuya** [comment]
I confirmed that #4 worked very well.

**Comment by gforcenova** [comment]
Japanese Page is updated with #2

**Comment by rotsuya** [comment]
I checked #2 and created new PR #10 . If you can agree with and merge PR #10, I will merge this PR.

**Pull request merged**
